#!/bin/bash
#
#
# Zuerst abfrage, ob BIOS-PW gesetzt ist; Returncode=0 JA

LOGFILE=$1
FEHLER=0

#
# Abfrage BIOS ja/nein (nein - RC=0)
#
zenity --question --default-cancel \
  --text="Microsoft Surface Laptop erkannt. Hat das Gerät ein BIOS-Passwort (default=nein)?\nAusserdem mit rechter Maustaste auf den Bildschirmhintergrund klicken, [Anzeigeeinstellungen] wählen und Skalieren auf 100% ändern " 
BIOS=$?

echo -e "\nSurface Laptop\n" | tee -a $LOGFILE

# set text scaling factor & passende Cursor Größe

gsettings set  org.gnome.desktop.interface text-scaling-factor 1.50
gsettings set  org.gnome.desktop.interface cursor-size 48

#
# Aufruf der Paketinstallation für den Surface Kernel
#
#
# Gefunden in https://github.com/linux-surface/linux-surface/
#
#
# First you need to import the keys we use to sign packages.
#

gpg --dearmor < /opt/APT/surface.asc | sudo dd of=/etc/apt/trusted.gpg.d/linux-surface.gpg
#
# After this you can add the repository configuration and update APT.
#
sudo cp /opt/APT/linux-surface.list /etc/apt/sources.list.d/linux-surface.list

sudo apt update 2>&1 | tee -a $LOGFILE

#
# Now you can install the linux-surface kernel and its dependencies.
#
for paket in linux-image-surface linux-headers-surface libwacom-surface iptsd
do

   sudo apt-get install $paket -y --no-download -o Dir::Cache::Archives=/opt/APT/ 2>&1 | tee -a  "$LOGFILE"

done 

#
# Wenn BIOS-PW gesetzt ist, muss dieses Zusatzpaket installiert werden
#
if [ $BIOS -eq 0 ]; then
   sudo apt-get install -linux-surface-secureboot-mok -y --no-download -o Dir::Cache::Archives=/opt/APT/ 2>&1 | tee -a  "$LOGFILE"
fi

#
# Update grub
#

sudo update-grub 2>&1 | tee -a $LOGFILE

echo ""
echo "Bitte Return eingeben"
echo ""
read a

