#!/bin/bash
# 
# Wird aufgerufen von _update_installation.sh
# Schreibt eigenes temp. Logfile, damit es auf Fehler untersucht werden kann.
#

if [ $UID -ne 0 ]; then
   exit $?
fi

logfile=$1

# ------------------------------------------------------------------------------------

echo -e "\nUpdate der Pakete\n"

echo ""                 > $logfile
apt update              2>&1 | tee -a $logfile
apt-get dist-upgrade -y 2>&1 | tee -a $logfile
apt autoremove -y       2>&1 | tee -a $logfile

# ------------------------------------------------------------------------------------
#

Fehler=$(egrep -c '^E:|Fehler beim Holen' $logfile)

if [ $Fehler -gt 0 ]; then
   echo -e "\n Es gab $Fehler Fehler beim Update; Netzwerk??? \n " | tee -a $logfile
   read a
else
   echo -e "\n Update ohne Fehler beendet \n" | tee -a $logfile
   sleep 10
fi
