#!/bin/bash
#

LOGFILE=$1

# set text scaling factor & passende Cursor Größe

gsettings set  org.gnome.desktop.interface text-scaling-factor 1.30
gsettings set  org.gnome.desktop.interface cursor-size 48

#
# Installiere die VMWare Tools
#
NETZ="$(nmcli -g NAME c show --active)"

#
# Aufruf der Paketinstallation 
#

for paket in open-vm-tools open-vm-tools-desktop 
do

   apt-get install \$paket -y --no-download -o Dir::Cache::Archives=/opt/APT/

done


echo ""
echo "Bitte Return eingeben"
echo ""
read a
