#!/bin/bash
#

LOGFILE=$1

# set text scaling factor & passende Cursor Größe

gsettings set  org.gnome.desktop.interface text-scaling-factor 1.30
gsettings set  org.gnome.desktop.interface cursor-size 48

#
# Installiere die VMWare Tools
#
NETZ="$(nmcli -g NAME c show --active)"

#
# Aufruf der Paketinstallation 
#

for paket in open-vm-tools open-vm-tools-desktop 
do

   sudo apt-get install $paket -y --no-download -o Dir::Cache::Archives=/opt/APT/

done 

#
# workaround for bug in shared devices
#
if [ $(grep -c vmhgfs-fuse /etc/fstab) -eq 0 ]; then
   cat >> /etc/fstab << EOD
#
# workaround for bug in shared devices
# 
vmhgfs-fuse   /mnt/hgfs    fuse    defaults,allow_other,_netdev    0    0
EOD
fi

echo ""
echo "Bitte Return eingeben"
echo ""
read a
